#! /bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

make all
sed 's/^KERNEL_HEADERS.*/KERNEL_HEADERS=""/' .config
make include/bits/sysnum.h
make DESTDIR="$1" install

mv "$1/lib"/* "$1/usr/lib"
rmdir "$1/lib"
